# config/train_config.yaml

model:
  cache_dir: "~/huggingface/hf_models"
  pretrained_model: "CompVis/stable-diffusion-v1-4"
  text_encoder: "openai/clip-vit-large-patch14"
  lora:
    r: 16
    alpha: 32

training:
  t2uv:
    batch_size: 2
    num_epochs: 10
    learning_rate: 0.0001
  i2uv:
    batch_size: 4
    num_epochs: 10
    learning_rate: 0.0001

data:
  cache_dir: "/mnt/ssdp3/datasets/atlas_large"
  split: "train"
  prompts_file: "data/atlas_prompt_50k.txt"

output:
  t2uv_dir: "checkpoints/t2uv/"
  i2uv_dir: "checkpoints/i2uv/"
  out_dir: "inference/"
  log_every: 10

# pretrained_model: "CompVis/stable-diffusion-v1-4"
# text_encoder: "openai/clip-vit-large-patch14"